# Generated by Django 4.2.19 on 2025-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "patient_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("identity_card", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
