# Generated by Django 4.2.19 on 2025-04-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=20, unique=True, verbose_name="房間號碼"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否顯示在列表"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationPatientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patientdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationPatient",
            fields=[
                (
                    "location",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patientdata",
                    ),
                ),
            ],
        ),
    ]
