# Generated by Django 4.2.19 on 2025-04-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="permission",),
    ]
