# Generated by Django 4.2.19 on 2025-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_permission"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="status",),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用"),
        ),
    ]
